application: harvest-scoreboard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "latest"

   
handlers:
- url: /js
  static_dir: client/app/js

- url: /css
  static_dir: client/app/css

- url: /img
  static_dir: client/app/img

- url: /lib
  static_dir: client/app/lib

- url: /partials
  static_dir: client/app/partials

- url: /.*
  script: main.app