application: harvest-scoreboard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "latest"
  
handlers:
- url: /app
  static_dir: app

- url: /partials
  static_dir: app/partials

- url: /.*
  script: main.app